[tox]
env_list =
    py308
    py311
    py313



[testenv]
description = run the tests with pytest
package = wheel
extras = test
wheel_build_env = .pkg
commands =
    pytest {tty:--color=yes} -vv {posargs}
